# Generated by Django 4.2.23 on 2025-07-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0011_alter_refundrequest_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá gốc"
                    ),
                ),
                (
                    "flash_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá Flash Sale"
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(verbose_name="Tổng số lượng"),
                ),
                (
                    "sold_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Đã bán"),
                ),
                (
                    "max_per_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Giới hạn mỗi người"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_sale_items",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm Flash Sale",
                "verbose_name_plural": "Sản phẩm Flash Sale",
                "db_table": "flash_sale_items",
            },
        ),
        migrations.CreateModel(
            name="FlashSaleTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên khung giờ"),
                ),
                (
                    "start_hour",
                    models.PositiveIntegerField(verbose_name="Giờ bắt đầu (0-23)"),
                ),
                (
                    "start_minute",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Phút bắt đầu (0-59)"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Thời lượng (phút)"
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(default=list, verbose_name="Các ngày trong tuần"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Khung giờ Flash Sale",
                "verbose_name_plural": "Khung giờ Flash Sale",
                "db_table": "flash_sale_time_slots",
                "ordering": ["start_hour", "start_minute"],
            },
        ),
        migrations.CreateModel(
            name="FlashSalePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá đã trả"
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mã đơn hàng"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="api.flashsaleitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_sale_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử mua Flash Sale",
                "verbose_name_plural": "Lịch sử mua Flash Sale",
                "db_table": "flash_sale_purchases",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="FlashSaleProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên chương trình"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("start_time", models.DateTimeField(verbose_name="Thời gian bắt đầu")),
                ("end_time", models.DateTimeField(verbose_name="Thời gian kết thúc")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Sắp diễn ra"),
                            ("active", "Đang diễn ra"),
                            ("ended", "Đã kết thúc"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_sale_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chương trình Flash Sale",
                "verbose_name_plural": "Chương trình Flash Sale",
                "db_table": "flash_sale_programs",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="flashsaleitem",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.flashsaleprogram",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flashsaleitem",
            unique_together={("program", "product")},
        ),
    ]
