# Generated by Django 4.1.7 on 2025-07-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_flashsaleitem_flashsaletimeslot_flashsalepurchase_and_more"),
        ("api", "0016_color_size_orderitem_color_name_orderitem_size_name_and_more"),
    ]

    operations = []
