# Generated by Django 4.1.7 on 2025-07-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_merge_20250712_2149"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flashsaleitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="flashsaleitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="flashsaleitem",
            name="program",
        ),
        migrations.RemoveField(
            model_name="flashsaleprogram",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="flashsalepurchase",
            name="item",
        ),
        migrations.RemoveField(
            model_name="flashsalepurchase",
            name="user",
        ),
        migrations.DeleteModel(
            name="FlashSaleTimeSlot",
        ),
        migrations.DeleteModel(
            name="FlashSaleItem",
        ),
        migrations.DeleteModel(
            name="FlashSaleProgram",
        ),
        migrations.DeleteModel(
            name="FlashSalePurchase",
        ),
    ]
