# Generated by Django 3.2.19 on 2025-07-14 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_flashsaleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Từ khóa tìm kiếm, cách nhau bởi dấu phẩy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name': 'Phân loại chi tiết',
                'verbose_name_plural': 'Phân loại chi tiết',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Phân loại chi tiết', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory'),
        ),
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_min', models.IntegerField(blank=True, help_text='Chiều cao tối thiểu (cm)', null=True)),
                ('height_max', models.IntegerField(blank=True, help_text='Chiều cao tối đa (cm)', null=True)),
                ('weight_min', models.IntegerField(blank=True, help_text='Cân nặng tối thiểu (kg)', null=True)),
                ('weight_max', models.IntegerField(blank=True, help_text='Cân nặng tối đa (kg)', null=True)),
                ('chest', models.CharField(blank=True, help_text='Vòng ngực (cm)', max_length=20)),
                ('waist', models.CharField(blank=True, help_text='Vòng eo (cm)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm (form rộng/hẹp)')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.size')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_guides', to='api.subcategory')),
            ],
            options={
                'verbose_name': 'Hướng dẫn size',
                'verbose_name_plural': 'Hướng dẫn size',
                'unique_together': {('subcategory', 'size')},
            },
        ),
    ]
