# Generated by Django 3.2.19 on 2025-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconfig',
            name='default_model',
            field=models.CharField(default='llama3.2:3b', max_length=100),
        ),
    ]
