# Generated by Django 3.2.19 on 2025-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_chatreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_mode',
            field=models.CharField(default='user_admin', max_length=50),
        ),
    ]
